Define localhost network
To deploy contracts to localhost network we need to define it in
hardhat.config.ts

Use `allowStubs` tag to solve error thrown or deployment:
```
Error: ERROR processing /Users/jakub/workspace/keep-network/tbtc-v2/solidity/node_modules/@threshold-network/solidity-contracts/export/deploy/00_resolve_keep_registry.js:
Error: deployed KeepRegistry contract not found
```