Change the range for gas usage for `Bridge.notifyMovingFundsTimeoutTx`
We saw following failure in the integration tests when `50_000` range
was used:
```
) Integration Test - Slashing
       notifyMovingFundsTimeout
         when wallet is created
           when moving funds timeout is reported
             should consume around 3 100 000 gas for
	     Bridge.notifyMovingFundsTimeoutTx transaction:
     AssertionError: invalid gas used: Expected "3049026" to be within 50000
     of 3100000
```
We're updating the range to have a wider marigin for the allowed gas usage.