Don't search for ESLint config files in parent directories
The `"root": true` config has been added to the `yearn/.eslintrc` file
to prevent ESLint from using config file in the parent directory.
Without this change, linting in the `yearn` directory was resulting with
following error:
```
Error: Cannot find module '@keep-network/prettier-config-keep'
```